### PR TITLE
Update for v4.0alpha14

### PR DESCRIPTION
**Pull request by blipk**
Hey, I found this useful and with v4 going into beta soon someone might find this useful.

I downloaded it from the asset store and I believe many of the changes are from the automatic 3to4 convertor, although I had to change a few extra lines as per the commit message.

### CODE REVIEW

**Comment by teebarjunk** [comment]
Oh I already had a Godot 4.0 version, which is in the store too:
https://github.com/teebarjunk/godot-4.0-tool_button
https://godotengine.org/asset-library/asset/1054

But it's probably old so if you have any changes for it I will accept them.

**Comment by blipk** [comment]
That's likely the version I downloaded then @teebarjunk as I got it directly from the asset store in v4.0alpha14.
There's been some breaking changes over the alpha version with some function signature changes, so I had to make a few changes to.
I will move this PR to your 4.0 repo.

**Comment by blipk** [comment]
Strange, the asset lib entry linked to this repo originally with 'View files', now it's linking to your 4.0 repo but it seems to still serve me the files from this repo.
Perhaps my editor is caching it?

**Comment by blipk** [comment]
Closed in favour of https://github.com/teebarjunk/godot-4.0-tool_button/pull/1

**Pull request closed without merging**
